---
name: 'AWS Credentials'
description: 'Configure AWS credentials for Terraform'
inputs:
  role-to-assume:
    description: 'AWS role to assume'
    required: true
  aws-region:
    description: 'AWS region'
    required: true
  aws-access-key-id:
    description: 'AWS access key ID'
    required: true
  aws-secret-access-key:
    description: 'AWS secret access key'
    required: true
  role-duration-seconds:
    description: 'AWS role duration in seconds'
    required: true
    default: '1200'

runs:
  using: 'composite'
  steps:
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: ${{ inputs.role-to-assume }}
        aws-region: ${{ inputs.aws-region }}
        aws-access-key-id: ${{ inputs.aws-access-key-id }}
        aws-secret-access-key: ${{ inputs.aws-secret-access-key }}
        role-duration-seconds: ${{ inputs.role-duration-seconds }}

    - name: Terraform Profile
      shell: bash
      id: profile
      run: |
        profile=${{ vars.AWS_PROFILE }}
        aws configure --profile "$profile" set "profile.${profile}.aws_access_key_id" ${{ env.AWS_ACCESS_KEY_ID }}
        aws configure --profile "$profile" set "profile.${profile}.aws_secret_access_key" ${{ env.AWS_SECRET_ACCESS_KEY }}
        aws configure --profile "$profile" set "profile.${profile}.aws_session_token" ${{ env.AWS_SESSION_TOKEN }}