---
jobs:
  changedfiles:
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      all: ${{ steps.changes.outputs.all}}
      tf: ${{ steps.changes.outputs.tf }}
      yml: ${{ steps.changes.outputs.yml }}
    steps:
        # Make sure we have some code to diff.
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Get changed files
        id: changes
        # Set outputs using the command.
        run: |
          echo "::set-output name=all::$(git diff --name-only --diff-filter=ACMRT ${{ github.event.commit.base.sha }} ${{ github.sha }} | xargs)"
          echo "::set-output name=tf::$(git diff --name-only --diff-filter=ACMRT ${{ github.event.commit.base.sha }} ${{ github.sha }} | grep .tf$ | xargs)"
          echo "::set-output name=yml::$(git diff --name-only --diff-filter=ACMRT ${{ github.event.commit.base.sha }} ${{ github.sha }} | grep .yml$ | xargs)"
  lint:
    runs-on: ubuntu-latest
    # require the first job to have ran
    needs: changedfiles
    # only run there are changed files
    if: ${{needs.changedfiles.outputs.tf != ''}} || ${{needs.changedfiles.outputs.yml != ''}}
    steps:
      - name: echo changed files
        run: |
          echo ${{needs.changedfiles.outputs.all}}
          echo ${{needs.changedfiles.outputs.tf}}
          echo ${{needs.changedfiles.outputs.yml}}
