---
name: Base Infra

on:
  pull_request:
    # types: [ closed ]
    branches:
      - main
      - uat
      - develop
    paths:
      - '.iac/base_infra/**'
      - '.github/workflows/base_infra.yml'
      - '.github/workflows/aws.yml'
      - '.github/workflows/changed-files.yml'
      - '.github/workflows/plan.yml'
      - '.github/workflows/apply.yml'
      - '.github/actions/dump-context/action.yml'
      - '.github/actions/changed-files/action.yml'
      - '.github/actions/aws-creds/action.yml'
  push:
    branches:
      - main
      - uat
      - develop
    paths:
      - '.iac/base_infra/**'
      - '.github/workflows/base_infra.yml'
      - '.github/workflows/aws.yml'
      - '.github/workflows/changed-files.yml'
      - '.github/workflows/plan.yml'
      - '.github/workflows/apply.yml'
      - '.github/actions/dump-context/action.yml'
      - '.github/actions/changed-files/action.yml'
      - '.github/actions/aws-creds/action.yml'
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
  release:
    types:
      - published
    paths:
      - '.iac/base_infra/**'
      - '.github/workflows/base_infra.yml'
      - '.github/workflows/aws.yml'
      - '.github/workflows/changed-files.yml'
      - '.github/workflows/plan.yml'
      - '.github/workflows/apply.yml'
      - '.github/actions/dump-context/action.yml'
      - '.github/actions/changed-files/action.yml'
      - '.github/actions/aws-creds/action.yml'

permissions:
  contents: read
  pull-requests: write

jobs:
  paths-filter:
    outputs:
      base_infra: ${{ steps.filter.outputs.base_infra }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            base_infra:
              - '.iac/base_infra/aws/**'
              - '.github/workflows/base_infra.yml'
              - '.github/workflows/aws.yml'
              - '.github/workflows/changed-files.yml'
              - '.github/workflows/plan.yml'
              - '.github/workflows/apply.yml'
              - '.github/actions/dump-context/action.yml'
              - '.github/actions/changed-files/action.yml'
              - '.github/actions/aws-creds/action.yml'
  deploy-aws:
    uses: ./.github/workflows/aws.yml
    secrets: inherit
    # uses: shortpoet/tf-web/.github/workflows/plan.yml@main
    if: steps.filter.outputs.base_infra == 'true'
    with:
      base_path: .iac/infra_base/aws
      infra_type: base
      provider: aws
