---
name: Deploy

env:
  BASE_PATH: '.iac/deploy'

on:
  pull_request:
    # types: [ closed ]
    branches:
      - main
      - uat
      - develop
    paths:
      - '.iac/deploy/**'
      - '.github/workflows/deploy.yml'
      - '.github/workflows/aws.yml'
      - '.github/workflows/changed-files.yml'
      - '.github/workflows/plan.yml'
      - '.github/workflows/apply.yml'
      - '.github/actions/dump-context/action.yml'
      - '.github/actions/changed-files/action.yml'
      - '.github/actions/aws-creds/action.yml'
      - 'shortpoet_site/**'
      - 'tic_tac_toe/**'
  push:
    branches:
      - main
      - uat
      - develop
    paths:
      - '.iac/deploy/**'
      - '.github/workflows/deploy.yml'
      - '.github/workflows/aws.yml'
      - '.github/workflows/changed-files.yml'
      - '.github/workflows/plan.yml'
      - '.github/workflows/apply.yml'
      - '.github/actions/dump-context/action.yml'
      - '.github/actions/changed-files/action.yml'
      - '.github/actions/aws-creds/action.yml'
      - 'shortpoet_site/**'
      - 'tic_tac_toe/**'
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
  release:
    types:
      - published
    paths:
      - '.iac/deploy/**'
      - '.github/workflows/deploy.yml'
      - '.github/workflows/changed-files.yml'
      - '.github/workflows/plan.yml'
      - '.github/workflows/apply.yml'
      - '.github/actions/dump-context/action.yml'
      - '.github/actions/changed-files/action.yml'
      - '.github/actions/aws-creds/action.yml'
      - 'shortpoet_site/**'
      - 'tic_tac_toe/**'

permissions:
  contents: read
  pull-requests: write

jobs:
  deploy-aws:
    uses: ./.github/workflows/aws.yml
    secrets: inherit
    # uses: shortpoet/tf-web/.github/workflows/plan.yml@main
    with:
      base_path: .iac/infra_app/aws
      infra_type: app
