---
name: Infra

on:
  push:
    branches:
      - main
      - develop
    paths:
      - '.iac/**'
      - '.github/workflows/infra.yml'
      - '.github/workflows/changed-files.yml'
      - '.github/.templates/plan.yml'

jobs:
  dump-context:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"


  changed-files:
    uses: shortpoet/tf-web/.github/workflows/changed-files.yml@main

  debug-changed-files:
    needs: changed-files
    runs-on: ubuntu-latest
    steps:
      - name: echo changed files
        run: |
          echo ${{needs.changed-files.outputs.all}}
          echo ${{needs.changed-files.outputs.tf}}
          echo ${{needs.changed-files.outputs.yml}}
    # with:
    #   path: '.iac'
  # build-plan:
  #   uses: shortpoet/tf-web/.github/.templates/plan.yml@main
