---
name: Base Infra

on:
  pull_request:
    # types: [ closed ]
    branches:
      - main
      - uat
      - develop
    paths:
      - '.iac/infra_base/**'
      - '.github/workflows/infra-base.yml'
      - '.github/workflows/deploy.yml'
      - '.github/workflows/changed-files.yml'
      - '.github/workflows/plan.yml'
      - '.github/workflows/apply.yml'
      - '.github/actions/dump-context/action.yml'
      - '.github/actions/changed-files/action.yml'
      - '.github/actions/aws-creds/action.yml'
  push:
    branches:
      - main
      - uat
      - develop
    paths:
      - '.iac/infra_base/**'
      - '.github/workflows/infra-base.yml'
      - '.github/workflows/deploy.yml'
      - '.github/workflows/changed-files.yml'
      - '.github/workflows/plan.yml'
      - '.github/workflows/apply.yml'
      - '.github/actions/dump-context/action.yml'
      - '.github/actions/changed-files/action.yml'
      - '.github/actions/aws-creds/action.yml'
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
  release:
    types:
      - published
    paths:
      - '.iac/infra_base/**'
      - '.github/workflows/infra-base.yml'
      - '.github/workflows/deploy.yml'
      - '.github/workflows/changed-files.yml'
      - '.github/workflows/plan.yml'
      - '.github/workflows/apply.yml'
      - '.github/actions/dump-context/action.yml'
      - '.github/actions/changed-files/action.yml'
      - '.github/actions/aws-creds/action.yml'

permissions:
  contents: read
  pull-requests: write

jobs:
  # dump-context:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Dump GitHub context
  #       env:
  #         GITHUB_CONTEXT: ${{ toJson(github) }}
  #       run: echo "$GITHUB_CONTEXT"
  
  paths-filter:
    if:
      (
        (startsWith(github.ref, 'refs/pull') &&
        endsWith(github.ref, '/merge') &&
        github.head_ref == 'uat' &&
        github.base_ref == 'main' &&
        github.event_name == 'pull_request')
      ) ||
      (github.event_name == 'push' && github.ref != 'refs/heads/uat') ||
      github.event_name == 'release'
    outputs:
      infra_base: ${{ steps.filter.outputs.infra_base }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            infra_base:
              - '.iac/infra_base/aws/**'
              - '.github/workflows/infra-base.yml'
              - '.github/workflows/deploy.yml'
              - '.github/workflows/changed-files.yml'
              - '.github/workflows/plan.yml'
              - '.github/workflows/apply.yml'
              - '.github/actions/dump-context/action.yml'
              - '.github/actions/changed-files/action.yml'
              - '.github/actions/aws-creds/action.yml'
  
  deploy-aws:
    uses: ./.github/workflows/deploy.yml
    secrets: inherit
    needs: paths-filter
    # uses: shortpoet/tf-web/.github/workflows/plan.yml@main
    if: needs.paths-filter.outputs.infra_base == 'true'
    with:
      base_path: .iac/infra_base/aws
      infra_type: Base
      provider: aws
